### ISSUE TITLE
SVG content get's truncated when persisted in DB

### ISSUE THREAD

**Issue by imileti** [rgomeztinoco/strapi-plugin-heroicons-field#1]
Look's like the data type should be `text`.

**Comment by rgomeztinoco** [comment]
Hi, can you tell me the icon with which this problem occurred?

**Comment by imileti** [comment]
Hi, I actually have this problem with all the icons I tried. The issue is slightly different in different environments.

**Localhost (Docker compose with `mysql:latest` for the `linux/amd64`**
- When saving content with a heroicon I see an error message saying something like 'content length is too long for ...'

**Production (ECS with MySql RDS)**
- I can save the content, but the icon value is truncated and I receive truncated values in the API
